{% set name = "types-seaborn" %}
{% set version = "0.13.2.20240417" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-seaborn-{{ version }}.tar.gz
  sha256: 130989a40d92a1256292c9693b62a7420f1747b25e0d74b6c156764a56ed10ec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - matplotlib-base >=3.8
    - numpy >=1.20
    - pandas-stubs

test:
  commands:
    - pip check
    - test -f $SP_DIR/seaborn-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\seaborn-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for seaborn
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - '0xbe7a'
