{% set name = "types-seaborn" %}
{% set version = "0.13.2.20240813" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-seaborn-{{ version }}.tar.gz
  sha256: b14d1bce1dd5e083c879b186706aa67a4f7bc196607d17b0a77f35ee4ffc8bd3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - pip
  run:
    - python >=3.9
    - matplotlib-base >=3.8
    - numpy >=1.20,<2
    - pandas-stubs

test:
  commands:
    - pip check
    - test -f $SP_DIR/seaborn-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\seaborn-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for seaborn
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - '0xbe7a'
